version: '3.9'

services:
  nostr-ngx-dev:
    image: nostr-ngx-dev
    container_name: nostr-ngx-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /nostr-ngx
    ports:
      - "4203:4203"
    volumes:
      - ..:/nostr-ngx:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
